#!/bin/bash

act=$1

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

case $act in
    load)
    cp kuara /bin/kuara
    cp kuara /sbin/kuara
    exit
        ;;
    unload)
    rm /bin/kuara
    rm /sbin/kuara
    exit
        ;;
    *)
    echo "No Action Promoted: Nothing Changed"
    ;;
esac
